### ISSUE TITLE
Redirection fin d'installation CLI

### ISSUE THREAD

**Issue by MedShake** [MedShake/MedShakeEHR-base#151]
Rapporté par @marsanté : 

"Bug qui touchait dans les versions précédentes uniquement les installations en différent conteneur de docker, mais qui touche depuis la version 8 les VM également. Après une installation en cli, le premier lancement de msehr.local ne redirige plus vers msehr.local/install.php ou vers la page de première connexion. Il faut manuellement aller sur msehr.local/install.php et une fois fait, taper msehr.local redirige comme avant."

**Comment by MedShake** [comment]
Je suis perdu. 
On parle bien de l'étape située en fin de self-installer.php  ou de debian-bash-installer.sh (ou équivalent à la main) ?

Si c'est bien ça, l'ouverture dans le navigateur lance l'index.php.
- en ligne 58 on regarde s'il y a un fichier config.yml sinon on redirige vers install.php 
- en ligne 77 on regarde s'il y a des modules installés, sinon on redirige là encore vers install.php

Il y a donc visiblement un trou quelque part. Mais où .. ?!

**Comment by marsante** [comment]
Dans vagrant et docker je n'utilise pas le self-installer.php, mais directement la cli

```yml
    - name: Execute MedShakeEHR cli installation script
      shell: "/usr/bin/php {{ msehrPath }}/public_html/install.php -s localhost -N -d {{ sqlDbName }} -u {{ sqlUserAccount }} -p \"{{ sqlUserPassword }}\" -r https -D {{ domain }} -o localhost"
      become: true
      become_user: www-data
      environment:
        MEDSHAKEEHRPATH: "{{ msehrPath }}"
      when: not ymlconfig.stat.exists
```

Suite à cette tâche apache est redémarré.
